### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by sladki7** [kaniol-lck/Kaminec#1]
how to install and run

**Comment by kaniol-lck** [comment]
Sorry,this project **hasn't been RELEASE** yet.
You can only compile it in Qt Creator(or VS,if you like.).
Also,put 7za.exe in the directory of the output program.
I'm trying to find a nice uncompress library.

Here's the 7za.exe :[7-Zip Extra](http://d.7-zip.org/a/7z1701-extra.7z)
